version: '3.8'
services:
  db:
    image: mysql:8.0
    volumes:
      - db-data:/var/lib/mysql
      - ./schema:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database_development
    ports:
      - "3306:3306"
  app:
    image: site_webnodejs
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: database_development
      DB_PORT: 3306

volumes:
  db-data:

networks:
  default: 
    name: app-network
